# profile environment
FROM openjdk:17-alpine

VOLUME ["/app_log/github-action-dev"]
LABEL project="github-action-dev"

ADD build/libs/github-action-test.jar github-action-test.jar
EXPOSE 8080
RUN sh -c 'touch /github-action-test.jar'
ENV JAVA_OPTS="-Dspring.profiles.active=dev"
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /github-action-test.jar"]