# profile environment
FROM openjdk:17-alpine

VOLUME ["/app_log/github-action-prod"]
LABEL project="github-action-prod"

ADD api/build/libs/github-action-test.jar github-action-test.jar
EXPOSE 8080
RUN sh -c 'touch /github-action-prod.jar'
ENV JAVA_OPTS="-Dspring.profiles.active=prod"
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /github-action-prod.jar"]