# profile environment
FROM openjdk:17-alpine

VOLUME ["/app_log/github-action-dev"]
LABEL project="github-action-dev"

ADD
EXPOSE 9000
RUN sh -c 'touch /github-action-test.jar'
ENV JAVA_OPTS="-Dspring.profiles.active=dev -Dserver.port=9000"
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /github-action-test.jar"]